version: 2

models:
  - name: stg_company_detail
    description: "company detail (W. sector info, industry info)"
    columns:
      - name: company_symbol
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: stg_news_external_table
    description: "External news data table (from S3 /news/)"
    columns:
      - name: content_id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: company_key
        description: "company foreign key"
        data_tests:
          - not_null
  - name: company_info
  - name: sector_info
  - name: industry_info