news:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: host
      user: useraccount
      password: userpassword
      role: ACCOUNTADMIN
      warehouse: "RAW_DATA"      
      database: DEV
      schema: '#'
      threads: 4
      client_session_keep_alive: false